### ISSUE TITLE
Startproposer timeout after each new startvalidator via CLI

### ISSUE THREAD

**Issue by hlooman** [olympus-protocol/ogen#124]
Startproposer does not return success status after adding a new validator via the CLI

### Expected behaviour

Success

### Actual behaviour

Returns the following error:
rpc error: code = DeadlineExceeded desc = context deadline exceeded

Noticed: ogen daemon does not crash or have any errors, but needs to be killed and restarted to make startproposer work properly again.

**Comment by eabz** [comment]
Should be fixed on #125

**Comment by eabz** [comment]
Just checked and seems fixed.
