### ISSUE TITLE
Version Message may cause a panic

### ISSUE THREAD

**Issue by Aether-eum** [olympus-protocol/ogen#140]
### Describe the issue

One node that was being tested panicked after receiving an invalid version message. 
The logs of the node were:
"received version message from 12D3KooWBHV2MWmCgnoQFzuTuuGfZvkk644TT6YkSW2nYtzM7isr
panic: division by zero"

**Example:**

Two nodes were created. One of them doesn't have validators, but started to send votes. At some point, it sent an incorrect version message, causing the other one to panic.

### Expected behaviour

An invalid version message should be deserialized and penalized, but by no means should panic the node.
### Actual behaviour

The node crashed.

**Comment by eabz** [comment]
I checked the interfaces for the `MsgVersion` and it is impossible to cause panics, but this might be related to the `syncprotocol` 

I think we need to do tests on the syncprotocol the panic may be there.
