### ISSUE TITLE
Exitvalidator only exits one validator per block

### ISSUE THREAD

**Issue by hlooman** [olympus-protocol/ogen#179]
### Describe the issue

Both on console and via rpc only the first exitvalidator command in a new block gets executed, subsequent exitvalidator commands result in success message but get ignored.

**Console Example:**

> exitvalidator 8fbb72672ef0bdb4281e4d85c27230c109b72c4a31128cc4a83aba727723e29c60eb56f307fdd0d153fc688c0b4515a0
{
  "success": true
}
> exitvalidator b9b0c961a19436762e967026bad9df7b0b2f48c1715f068ec2d798815039495f1673fc03b49dbecdcac101c386b45c16
{
  "success": true
}

### Expected behaviour

Both validators should go to status Pending Exit

### Actual behaviour

Only the first validator goes to Pending Exit status, the second one stays status Active

Verified this behaviour both via console and rpc

**Comment by eabz** [comment]
Fixed on #195 
There was an error on a validation on mempool additions
