### ISSUE TITLE
Add Command To Fetch Active Wallet's Validators Status Only

### ISSUE THREAD

**Issue by cryptosharks131** [olympus-protocol/ogen#204]
After you get a certain number of validators on your node, the `getvalidators` command will become too long to effectively use and you may no longer be able to view the count of validators you have.

I propose adding a new command such as `getvalidatorstatus`, this will return a smaller response without the entire list of wallet validators.

Example:
Total: 1
Active: 1
Starting: 0
Exited: 0
Total Coins Locked: 100

**Comment by eabz** [comment]
Added:
- Console `getvalidatorscount`
- API `/wallet/validatorscount`
